project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "CAGED Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Products"
        href: products.qmd
    right:
      - text: "People"
        href: people.qmd
      - icon: github
        href: https://github.com/lter/lterwg-caged

format:
  html:
    theme:
       light: theme_light.scss
       dark: theme_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
