project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "CAGED Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
