project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "CAGED"
  favicon: images/CAGED_Bison_bison_notext.png
  navbar:
    left:
      - text: "Products"
        href: products.qmd
    right:
      - text: "People"
        href: people.qmd
      - icon: github
        href: https://github.com/lter/lterwg-caged

format:
  html:
    theme:
       light: theme_light.scss
       dark: theme_dark.scss
    mainfont: Open Sans
    toc: false
    link-external-newwindow: true
    link-external-icon: false
